name: la_ziyofat_restaurant
description: Bismillah.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  lottie: ^2.2.0
  animated_native_splash: ^1.3.0
  provider: ^6.0.2
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.17
  page_route_animator: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/splash1.json
    - assets/traslaton/
    - assets/


#  fonts:
#    - family: Manrope
#      fonts:
#        - asset: assets/fonts/Manrope-Regular.ttf
#          style: italic


animated_native_splash:
  jsonFile: assets/animations/splash1.json
