// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmiP2FKuxNN8Ww4tg--1xdFENa_MXsSTY',
    appId: '1:88334176996:web:a6fe1fef2b1096efd592f1',
    messagingSenderId: '88334176996',
    projectId: 'la-ziyofat-restaurant',
    authDomain: 'la-ziyofat-restaurant.firebaseapp.com',
    storageBucket: 'la-ziyofat-restaurant.appspot.com',
    measurementId: 'G-57DMV5HDBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzDYd2TVQaEBApp0ec4t7IIKZjXNy98xM',
    appId: '1:88334176996:android:fc0b47e6531ea05fd592f1',
    messagingSenderId: '88334176996',
    projectId: 'la-ziyofat-restaurant',
    storageBucket: 'la-ziyofat-restaurant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtNF_DZWFaN847gJajEXrXfWpDXWN8Bwo',
    appId: '1:88334176996:ios:4cd20387b1dbc716d592f1',
    messagingSenderId: '88334176996',
    projectId: 'la-ziyofat-restaurant',
    storageBucket: 'la-ziyofat-restaurant.appspot.com',
    iosClientId: '88334176996-i18soavde5fhsfc7m04rpbsau3766au0.apps.googleusercontent.com',
    iosBundleId: 'uz.laziyofat.restaurant.uz.laZiyofatRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtNF_DZWFaN847gJajEXrXfWpDXWN8Bwo',
    appId: '1:88334176996:ios:4cd20387b1dbc716d592f1',
    messagingSenderId: '88334176996',
    projectId: 'la-ziyofat-restaurant',
    storageBucket: 'la-ziyofat-restaurant.appspot.com',
    iosClientId: '88334176996-i18soavde5fhsfc7m04rpbsau3766au0.apps.googleusercontent.com',
    iosBundleId: 'uz.laziyofat.restaurant.uz.laZiyofatRestaurant',
  );
}
